### ISSUE TITLE
Fix for some atypical excel files

### ISSUE THREAD

**Issue by alexfunkbahn** [pjfanning/excel-streaming-reader#201]
We had trouble handling some excel files in our spark/scala data pipelines, and below might be the root cause.
The excels appear to be legal, given the fact that excel opens them, and schema definitions do not seem to contradict.
If we do read the excels we get stack traces like this:
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "19149 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.getFormatterForType(StreamingRowIterator.java:507)
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.formattedContents(StreamingRowIterator.java:495)
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.handleEvent(StreamingRowIterator.java:317)
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.getRow(StreamingRowIterator.java:121)
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.<init>(StreamingRowIterator.java:103)
	at com.github.pjfanning.xlsx.impl.StreamingSheetReader.iterator(StreamingSheetReader.java:265)
	at com.github.pjfanning.xlsx.impl.StreamingSheetReader.getFirstRowNum(StreamingSheetReader.java:165)
	at com.github.pjfanning.xlsx.impl.StreamingSheet.getFirstRowNum(StreamingSheet.java:104)
	at com.crealytics.spark.excel.v2.CellRangeAddressDataLocator.rowIndices(DataLocator.scala:106)
	at com.crealytics.spark.excel.v2.CellRangeAddressDataLocator.readFrom(DataLocator.scala:84)
	at com.crealytics.spark.excel.v2.ExcelHelper.getSheetData(ExcelHelper.scala:140)
	at com.crealytics.spark.excel.v2.ExcelHelper.parseSheetData(ExcelHelper.scala:160)
	at com.crealytics.spark.excel.v2.ExcelTable.infer(ExcelTable.scala:77)
	at com.crealytics.spark.excel.v2.ExcelTable.inferSchema(ExcelTable.scala:48)
	at org.apache.spark.sql.execution.datasources.v2.FileTable.$anonfun$dataSchema$4(FileTable.scala:70)
```
Note the blank after the 19149.
[extra_whitespace.xlsx](https://github.com/pjfanning/excel-streaming-reader/files/12586873/extra_whitespace.xlsx)

I created a small/minimal excel that is attached here to demonstrate the issue, along with some fix. I could create a pull request but I have read creating an issue is preferred in this project first. The problem can be demonstrated with this test:
```
@Test
  public void testGetFirstRowNum() throws Exception {
    try (
            InputStream is = new FileInputStream("src/test/resources/extra_whitespace.xlsx");
            Workbook wb = StreamingReader.builder().open(is);
    ) {
      int firstRow = wb.getSheetAt(0).getFirstRowNum();
      assertEquals(0, firstRow);
    }
  }
``` 

Best regards, Alex

**Comment by pjfanning** [comment]
Does POI handle these files? spark-excel uses POI directly if you don't enable streaming.

**Comment by alexfunkbahn** [comment]
Just gave it a try: Yes, I can open my sample them with Apache POI.
