### ISSUE TITLE
ParseException: Error reading XML stream - too many columns

### ISSUE THREAD

**Issue by mike-podolskiy90** [pjfanning/excel-streaming-reader#240]
I got this stacktrace while processing an excel file:

```
Error writing data file ..., line 99
	...
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
Caused by: com.github.pjfanning.xlsx.exceptions.ParseException: Error reading XML stream
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.getRow(StreamingRowIterator.java:129) ~[excel-streaming-reader-4.2.1.jar:?]
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.hasNext(StreamingRowIterator.java:630) ~[excel-streaming-reader-4.2.1.jar:?]
	...
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[2,49025]
Message: null
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:599) ~[?:1.8.0_362]
	at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83) ~[?:1.8.0_362]
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.getRow(StreamingRowIterator.java:124) ~[excel-streaming-reader-4.2.1.jar:?]
	at com.github.pjfanning.xlsx.impl.StreamingRowIterator.hasNext(StreamingRowIterator.java:630) ~[excel-streaming-reader-4.2.1.jar:?]
	...
```

It seems there are too many (empty?) columns in the file. Files are uploaded by users so I can't control them. Is there a way I can prevent it from happening?

Thank you!

**Comment by pjfanning** [comment]
I will need a reproducible test case to do anything here.

**Comment by mike-podolskiy90** [comment]
How I create `Workbook`:

```java
    return StreamingReader.builder()
      .rowCacheSize(1000)
      .bufferSize(4096)
      .setSharedStringsImplementationType(SharedStringsImplementationType.TEMP_FILE_BACKED)
      .setReadSharedFormulas(true)
      .setEncryptSstTempFile(true)
      .open(file);
```

**Comment by mike-podolskiy90** [comment]
Do you need an excel file?

**Comment by pjfanning** [comment]
Yes - I will not be able to reproduce this without an input file.

**Comment by mike-podolskiy90** [comment]
[2023_11_27_occurence_extension.xls](https://github.com/pjfanning/excel-streaming-reader/files/14213399/2023_11_27_occurence_extension.xls)

**Comment by mike-podolskiy90** [comment]
Indeed, simple reading works. But the problem still occurs: there is something wrong with the way I use it later. I'll try to make a simplified example to figure it out

**Comment by mike-podolskiy90** [comment]
Here's the gist how it's used. All unnecessary stuff removed, but issue still happens
https://gist.github.com/mike-podolskiy90/836efe90cd06afd505e8f766ec441c4e

Test:
https://gist.github.com/mike-podolskiy90/a724740a1236c604b72f0854a8eebabc

**Comment by pjfanning** [comment]
@mike-podolskiy90 with all due respect, I'm going to leave debugging that up to you. Maybe, you could add some checks for nulls to avoid the NullPointerException. As far as I'm concerned, this lib works ok when you use its APIs. Wraps them up in your own iterators, then you have the responsibility for that.

**Comment by mike-podolskiy90** [comment]
Thank you for checking anyway. I was hoping you can spot something right away. I think there is something wrong with how it manages/closes resources. I'll figure that out.
