### ISSUE TITLE
Reading first row from first sheet before full file available?

### ISSUE THREAD

**Issue by david5w** [pjfanning/excel-streaming-reader#38]
Thank you for this library.  Is it reasonable to expect this library to enable access to the first row in the first sheet, when the file is not yet completely available (still sequentially arriving)?  Based on the nature of the error, it seems like the underlying ZIP might disallow this.

When I try the following, I get the resulting exception.

	List<String> list = new LinkedList<String>();
	InputStream in = <...>
	try (
		Workbook workbook = StreamingReader.builder().open(in)) {
		Sheet sheet = workbook.getSheetAt(0);
		Row r = sheet.getRow(0);
		for (Cell c : r) {
			list.add(c.getStringCellValue());
		}
	}

org.apache.poi.openxml4j.exceptions.InvalidOperationException: Can't open the specified file: '<...>.xlsx'
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:137)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:252)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:201)
	at com.github.pjfanning.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:117)
	at com.github.pjfanning.xlsx.impl.StreamingWorkbookReader.init(StreamingWorkbookReader.java:93)
	at com.github.pjfanning.xlsx.StreamingReader$Builder.open(StreamingReader.java:247)
	<...>
Caused by: java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1585)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1439)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1448)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1249)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1211)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:701)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:185)
	at org.apache.poi.openxml4j.util.ZipSecureFile.<init>(ZipSecureFile.java:105)
	at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipFile(ZipHelper.java:158)
	at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:135)
	<...>

**Comment by pjfanning** [comment]
This is not an issue in this library. The exception happens in java.util.zip.ZipFile

**Comment by david5w** [comment]
Understood.  But it might be worthwhile to clarify to your audience that your streaming API cannot control whether any of its dependencies do non-streaming things (case in point), and that the memory and speed benefits of streaming may therefore be adversely impacted.  For our use case, it meant we couldn't use this library.  Nevertheless, thank you for making this library available.  Kind Regards.

________________________________

**Comment by pjfanning** [comment]
https://github.com/pjfanning/excel-streaming-reader/issues/103#issuecomment-1068119418

**Comment by oviniciuslara** [comment]
@david5w did you find a way to fit your use case?

**Comment by david5w** [comment]
We have not.

________________________________
